# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 01:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
