# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categoria', models.CharField(max_length=200)),
                ('codigo_atc', models.CharField(max_length=200)),
                ('nombre_medicamento', models.CharField(max_length=200)),
                ('contentracion', models.CharField(max_length=200)),
                ('forma_farmaceutica', models.CharField(max_length=200)),
                ('via_de_administracion', models.CharField(max_length=200)),
                ('envase_primario', models.CharField(max_length=200)),
                ('nivel_de_atencion', models.CharField(max_length=200)),
                ('establecimiento', models.CharField(max_length=200)),
                ('lista_complementaria', models.CharField(max_length=200)),
                ('antibiotico_reserva', models.CharField(max_length=200)),
                ('restriccion_uso', models.CharField(max_length=200)),
                ('uaps', models.BooleanField(default=False)),
                ('cis', models.BooleanField(default=False)),
                ('p', models.BooleanField(default=False)),
                ('hb', models.BooleanField(default=False)),
                ('hg', models.BooleanField(default=False)),
                ('hesp', models.BooleanField(default=False)),
                ('inst', models.BooleanField(default=False)),
                ('hpsiq', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opsApp.CategoriaMedicamento')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriaMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200)),
                ('SubSubCatetoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='categoriamedicamento',
            name='sub_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opsApp.SubCategoriaMedicamento'),
        ),
    ]
