# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0002_auto_20190921_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriamedicamento',
            name='SubSubCatetoria',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
