# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0004_auto_20190922_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvasePrimario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_embase', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='envase_primario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opsApp.EnvasePrimario'),
        ),
    ]
