# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0005_auto_20190922_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nivel', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nivel_de_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opsApp.NivelAtencion'),
        ),
    ]
