# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0006_auto_20190922_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegundaSubCategoriaMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200)),
                ('SubSubCatetoria', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='segunda_subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opsApp.SegundaSubCategoriaMedicamento'),
            preserve_default=False,
        ),
    ]
