# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0010_auto_20190922_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosGaceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(max_length=200, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_via_administracion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
    ]
