# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-01 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0012_medicamento_establecimiento2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='establecimiento2',
        ),
        migrations.AddField(
            model_name='archivosgaceta',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Establecimiento',
        ),
    ]
