# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0013_auto_20191001_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosgaceta',
            name='imagen_vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
