# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0014_archivosgaceta_imagen_vista_previa'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_link', models.CharField(max_length=200, null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
    ]
