# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0015_link_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='contentracion',
            field=models.CharField(max_length=1000),
        ),
    ]
