# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0018_auto_20191118_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_ios_descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_link', models.CharField(max_length=200, null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='link_descarga',
            new_name='link_android_descarga',
        ),
    ]
