# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0019_auto_20191120_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamedicamento',
            name='correlativo',
            field=models.IntegerField(null=True),
        ),
    ]
