# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0021_medicamento_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sugerencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=200, null=True)),
                ('cuerpo', models.TextField()),
                ('estado', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
