# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0022_sugerencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='contentracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
