# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0025_auto_20191218_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='viasdeadministracion',
            name='valor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
