# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0026_viasdeadministracion_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viasdeadministracion',
            name='valor',
        ),
    ]
