# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-20 01:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0030_auto_20191219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='restriccion_uso',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
