# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-20 01:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0033_auto_20191219_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='antibiotico_reserva',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
