# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0036_ayuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayuda',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
