# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0037_ayuda_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencias',
            name='estado',
        ),
    ]
