# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0038_remove_sugerencias_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerencias',
            old_name='titulo',
            new_name='asunto',
        ),
    ]
