# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsApp', '0039_auto_20200203_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerencias',
            old_name='asunto',
            new_name='titulo',
        ),
    ]
